### ISSUE TITLE
Incorrect Request: not enough parameters

### ISSUE THREAD

**Issue by nheath** [milgner/TeamCityRedmine#6]
I recently updated both my teamcity installation and the TeamCityRedmine plugin to the latest available. I'm using TeamCity Professional 7.1.1 (build 24074).

While configuring the plugin, I entered the server url and my API token, and am able to "Test connection" successfully. In the build history when a change notes references a redmine issue number, the regex matches correctly and a link and drop down arrow are inserted; the link works fine, however, I get an error when opening the issue summary drop down box.

The bold error text reads: "**Incorrect Request: not enough parameters.**"

The easiest way to troubleshoot this issue is probably to look at the redmine server logs and provide more detail. I will forward that request on to our IT department, to see if I can get any additional information. However, I wanted to mention it either way, in case that it similarly affects other users, or is an obvious fix.

**Comment by milgner** [comment]
Thanks for the update. I'm very busy with other projects at the moment, but I'll try to find the time to look into it during the weekend...

**Comment by minneyar** [comment]
I'm having this same issue with Teamcity 7.1 (build 23907).  Let me know if there's anything I can do to help.

**Comment by francm** [comment]
Same issue on TeamCity 8.0.4 (build 27616)

**Comment by kozimiro** [comment]
Me too 
TeamCity 8.0.5 (build 27692)

**Comment by milgner** [comment]
Thanks for the hint. What's your Redmine version?

**Comment by kozimiro** [comment]
Environment:
  Redmine version                       2.3.1.stable
  Ruby version                            1.9.3 (x86_64-linux)
  Rails version                            3.2.13
  Environment                             production
  Database adapter                     PostgreSQL
Redmine plugins:
  human_resources                     0.0.1
  redmine_git_hosting                  0.6.2
  redmine_plugin_views_revisions 0.0.1
  sidebar_hide                             0.0.3

**Comment by milgner** [comment]
Thanks! I'll have a look. It seemed to work fine when I made the version bump after TC8 compatibility a few months back, but it's clearly time I showed this plugin some love again :)

**Comment by kozimiro** [comment]
Thank you! Sorry, but on other TeamCities  7.1.3 (build 24266) and 7.1.5 (build 24400) i have the same issue

**Comment by milgner** [comment]
Hmm... since the TC API changed between 7 and 8, it will probably be additional work to continue supporting both versions. Would it be okay if we focussed on getting it to work on 8, first?

**Comment by kozimiro** [comment]
Sure, I posted it just for information :)

**Comment by milgner** [comment]
Could you please check with the new release, v1.2? I just fixed some SSL related errors and could not reproduce any errors with my Redmine 2.3.2.stable.

**Comment by ohde** [comment]
It works in IE, but not Chrome for me.

I checked v1.2 and I am still receiving "Incorrect Request: not enough parameters." in the drop down box. Chrome console reads "Consider using 'dppx' units instead of 'dpi', as in CSS 'dpi' means dots-per-CSS-inch, not dots-per-physical-inch, so does not correspond to the actual 'dpi' of a screen. In media query expression: (-webkit-min-device-pixel-ratio: 1.5), not all, not all, not all, (min-resolution: 144dpi), (min-resolution: 1.5dppx) "

**Comment by milgner** [comment]
Ah yes, now that you mention it, I remember some browser misbehaving and ignoring the query parameters when sending the AJAX GET request. I'll look into it, hopefully it can be fixed easily. So far, IE and Firefox work, not sure what Chrome is doing there.

**Comment by milgner** [comment]
Finally found the problem. It's actually related to TeamCity, see http://youtrack.jetbrains.com/issue/TW-35477 for further info. For now I recommend changing the ticket pattern to something that does not contain special characters like `#`.

**Comment by milgner** [comment]
@maohde I've also created a new ticket #10 to style the popup. What you're seeing right now is the default from TeamCity, but I hope I can find some way to hook in there.

**Comment by ohde** [comment]
Thanks for the find, I removed # from the ticket pattern and it works great. I will be sure to follow #10, to keep informed. Thanks again for the great plugin.

**Comment by milgner** [comment]
You're certainly welcome. Feel free to submit any issues or enhancement requests you have.
